package main

//go:generate go run magicmap.codegen.go

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

// This code will generate the magic map structures for various bit configurations.

func main() {

	// Read the template file
	templfile, err := filepath.Abs("magicmap.tpl")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting absolute path: %v\n", err)
		os.Exit(1)
	}
	tmplData, err := os.ReadFile(templfile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading template: %v\n", err)
		os.Exit(1)
	}

	// Parse the template
	tmpl, err := template.New("magicmap").Parse(string(tmplData))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	createSourceFile(tmpl, 12, 6) // 4096/64
	createSourceFile(tmpl, 11, 6) // 2048/64
	createSourceFile(tmpl, 10, 6) // 1024/64
	createSourceFile(tmpl, 10, 7) // 1024/128
	createSourceFile(tmpl, 10, 8) // 1024/256 // this causes an issue because 256 does not fit !!

	createSourceFile(tmpl, 9, 7) // 512/128
	createSourceFile(tmpl, 7, 6) // 128/64
	createSourceFile(tmpl, 6, 4) // 64/16
	createSourceFile(tmpl, 6, 3) // 64/8
	createSourceFile(tmpl, 5, 4) // 32/16

}

func createSourceFile(tmpl *template.Template, inbit, outbit int) {

	// Execute the template with the configurations
	var buf bytes.Buffer

	if outbit > 8 || inbit < outbit {
		fmt.Fprintf(os.Stderr, "Invalid bit configuration: %d -> %d\n", inbit, outbit)
		os.Exit(1)
	}

	fmt.Fprintf(&buf, "// Code generated by magicmap.codegen.go. DO NOT EDIT.\n// Generated on %s\n", time.Now())
	fmt.Fprintf(&buf, "// Input : %d bits (up to %d keys) -> Output : %d bits (up to %d values)\n", inbit, 1<<inbit, outbit, 1<<outbit)
	fmt.Fprintf(&buf, "\n\n")

	err := tmpl.Execute(&buf, struct {
		IN  int
		OUT int
	}{inbit, outbit})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	// Write the generated code to magicmap_generated.go
	fname := fmt.Sprintf("magicmap_generated_%d_%d.go", inbit, outbit)
	fname = filepath.Join("..", "position", fname)
	err = os.WriteFile(fname, buf.Bytes(), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", fname, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s successfully!", fname)
}
