package main

//go:generate go run magicmap.codegen.go

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

// This code will generate the magic map structures for following bit configurations.

type BitConfig struct {
	IN  int
	OUT int
}

var CodegenConfigs = []BitConfig{
	{IN: 13, OUT: 6},
	{IN: 12, OUT: 6},
	{IN: 11, OUT: 6},
	{IN: 10, OUT: 6},
	{IN: 10, OUT: 7},
	{IN: 10, OUT: 8},
	{IN: 9, OUT: 7},
	{IN: 7, OUT: 6},
	{IN: 6, OUT: 4},
	{IN: 6, OUT: 3},
	{IN: 5, OUT: 4},
}

const targetDir = "magic"

func main() {

	// Read the template file
	templfile, err := filepath.Abs("magicmap.tpl")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting absolute path: %v\n", err)
		os.Exit(1)
	}
	tmplData, err := os.ReadFile(templfile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading template: %v\n", err)
		os.Exit(1)
	}

	// Parse the template
	tmpl, err := template.New("magicmap").Parse(string(tmplData))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	for _, cfg := range CodegenConfigs {
		createSourceFile(tmpl, cfg.IN, cfg.OUT)
	}

	// create factory function
	createFactory()

}

func createSourceFile(tmpl *template.Template, inbit, outbit int) {

	// Execute the template with the configurations
	var buf bytes.Buffer

	if outbit > 8 || inbit < outbit {
		fmt.Fprintf(os.Stderr, "Invalid bit configuration: %d -> %d\n", inbit, outbit)
		os.Exit(1)
	}

	fmt.Fprintf(&buf, "// Code generated by magicmap.codegen.go. DO NOT EDIT.\n// Generated on %s\n", time.Now())
	fmt.Fprintf(&buf, "// Input : %d bits (up to %d keys) -> Output : %d bits (up to %d values)\n", inbit, 1<<inbit, outbit, 1<<outbit)
	fmt.Fprintf(&buf, "\n\npackage %s\n\n", targetDir)

	err := tmpl.Execute(&buf, struct {
		IN  int
		OUT int
	}{inbit, outbit})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	// Write the generated code to magicmap_generated.go
	fname := fmt.Sprintf("magicmap_generated_%d_%d.go", inbit, outbit)
	fname = filepath.Join("..", targetDir, fname)
	err = os.WriteFile(fname, buf.Bytes(), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", fname, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s successfully!\t(%d/%d)\n", fname, 1<<inbit, 1<<outbit)
}

func createFactory() {

	// load template
	templfile, err := filepath.Abs("magicmapfactory.tpl")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting absolute path: %v\n", err)
		os.Exit(1)
	}
	tmplData, err := os.ReadFile(templfile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading template: %v\n", err)
		os.Exit(1)
	}

	// Parse the template
	tmpl, err := template.New("magicmapfactory").Parse(string(tmplData))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Execute the template with the configurations
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by magicmap.codegen.go. DO NOT EDIT.\n// Generated on %s\n", time.Now())
	fmt.Fprintf(&buf, "\n\npackage %s\n\n", targetDir)
	fmt.Fprintf(&buf, "\n\n")
	err = tmpl.Execute(&buf, CodegenConfigs)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	// save to file
	fname := filepath.Join("..", targetDir, "magicmap_generated_factory.go")
	err = os.WriteFile(fname, buf.Bytes(), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", fname, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s successfully!\n", fname)

}
