// Code generated by magicmap.codegen.go. DO NOT EDIT.
// Generated on 2025-02-27 21:36:50.935082 +0100 CET m=+0.044160801


package magic




import "fmt"

// Create a implementation for the specified nb of bits in input and output.
func NewMagicMap(in, out int) (mm MagicMap) {

	switch {
	case in == 13 && out == 6:
		return NewMagicMap_13_6()
	case in == 12 && out == 6:
		return NewMagicMap_12_6()
	case in == 11 && out == 6:
		return NewMagicMap_11_6()
	case in == 10 && out == 6:
		return NewMagicMap_10_6()
	case in == 10 && out == 7:
		return NewMagicMap_10_7()
	case in == 10 && out == 8:
		return NewMagicMap_10_8()
	case in == 9 && out == 7:
		return NewMagicMap_9_7()
	case in == 7 && out == 6:
		return NewMagicMap_7_6()
	case in == 6 && out == 4:
		return NewMagicMap_6_4()
	case in == 6 && out == 3:
		return NewMagicMap_6_3()
	case in == 5 && out == 4:
		return NewMagicMap_5_4()
	default:
		// Handle the case when no matching function exists
		panic(fmt.Sprintf("No magic map function exists for size=%d, index=%d", in, out))
	}
}

