// Code generated by magicmap.codegen.go. DO NOT EDIT.
// Generated on 2025-02-27 20:44:23.5128289 +0100 CET m=+0.043298801
// Input : 7 bits (up to 128 keys) -> Output : 6 bits (up to 64 values)


package magic


import (
	"fmt"
	"unsafe"
)


// ====================================================
// 7 bits -> 6 bits
// ====================================================

func NewMagicMap_7_6() MagicMap {
	mm := new(magicMap_7_6)
	mm.magic = defaultmagic
	return mm
}

type magicMap_7_6 struct { // capa is 4096 in/64 out
	zerovalue uint64           // value for the '0' key
	keys   [1<<7]uint64 // keyindex ->  input keys
	index  [1<<7]uint8  // keyindex -> valueindex ( NOTE : assumes index < 256 for up to 256 distict output values per magicmap).
	values [1<<6]uint64  // valueindex -> output values
	nbin   uint16        // nb of keys registered, not counting 0
	nbout  uint8         // nb of keys and values registered, not counting 0
	magic uint64
}

func (mm *magicMap_7_6) SetMagic(magic uint64) (MagicMap){
	if magic == 0 {
		panic("trying to set magic to 0 is illegal and useless")
	}
	mm.magic = magic
	return mm
}

// Get implements MagicMap.
func (mm magicMap_7_6) Get(key uint64) (value uint64) {

	const maxin = 1 << 7
	if key == 0 {
		return mm.zerovalue
	}
	// look for key, linear search if collision, return 0 if not found
	keyindex := mm.hash(key)
	for {
		if mm.keys[keyindex] == 0 {
			return 0 // not found
		}
		if mm.keys[keyindex] == key {
			return mm.values[mm.index[keyindex]]
		}
		keyindex = (keyindex + 1) & (maxin - 1)
	}
}

func (mm magicMap_7_6) Size() (bytes int) {
	return int(unsafe.Sizeof((mm)))
}

func (mm magicMap_7_6) Count() (in, out int) {
	return int(mm.nbin), int(mm.nbout)
}

func (mm magicMap_7_6) Capa() (in, out int) {
	return 1<<7, 1 << 6
}

func (mm *magicMap_7_6) Set(key, value uint64) {
	const maxin = 1 << 7
	const maxout = 1 << 6

	if key == 0 {
		mm.zerovalue = value
		return
	}

	// check remaining capacity
	if mm.nbout == maxout-1 {
		panic("trying to set a new value beyond value capacity")
	}
	if mm.nbin == maxin {
		panic("trying to set a new key beyond key capacity")
	}
	if key == 0 {
		panic("key cannot be 0")
	}
	// look for value if it exists
	var valueindex uint8
	found := false
	for valueindex = 0; valueindex < mm.nbout; valueindex++ {
		if mm.values[valueindex] == value {
			found = true
			break
		}
	}
	// value was not previously known, lets register it.
	if !found {
		valueindex = uint8(mm.nbout)
		mm.values[mm.nbout] = value
		mm.nbout++
	}
	fmt.Printf("DEBUG : registerd value %d with valueindex %d\n", value, valueindex)
	// OK, now we have the index for the value in valueIndex.

	// look for key, linear search until empty slot found
	keyindex := mm.hash(key)
	for i := 0; i < (maxin); i = (i + 1) & (maxin - 1) { // never more than 2^12 tries
		if mm.keys[keyindex] == 0 {
			mm.keys[keyindex] = key
			mm.index[keyindex] = valueindex
			mm.nbin++
			return
		}
	}
	panic("internal logic error")
}

func (mm magicMap_7_6) AllKeys() []uint64 {
	keys := make([]uint64, 0, mm.nbin)
	for _, k := range mm.keys {
		if k != 0 {
			keys = append(keys, k)
		}
	}
	return keys
}

func (mm magicMap_7_6) AllValues() (values []uint64) {
	return append(values, mm.values[:mm.nbout]...)
}


func (mm magicMap_7_6) Dump() {
	maxin, maxout := mm.Capa()
	nbin, nbout := mm.Count()
	size := mm.Size()
	fmt.Printf("MagicMap : %d/%d keys, %d/%d values (memory used : %d bytes)\n", nbin, maxin, nbout, maxout, size)
	st := mm.Stats()
	fmt.Printf("Stats : %d collision, average search length %.2f, max search length %d\n", st.Coll, float64 (st.Sumsearch)/float64(nbin), st.Maxsearch )
	fmt.Printf("0-key :   %016X (%20d) -> %016X (%20d)\n",  0,0, mm.zerovalue, mm.zerovalue)	
	for i, k := range mm.AllKeys() {
		v := mm.Get(k)
		fmt.Printf("%05d :   %016X (%20d) -> %016X (%20d)\n", i, k, k, v, v)
	}
}


// 16 bits hash function optimized for speed
func (mm magicMap_7_6)  hash(key uint64) uint16 {
	return uint16((key * mm.magic) >> 24) & (1<<7-1) // middle bits have the most entropy
}

// Analyse the collisions in this map
func (mm magicMap_7_6) Stats() (st MagicStats) {

	maxin := 1<< 7

	for i,k := range mm.keys {
		if k != 0  {
			h := mm.hash(k)
			if mm.keys[h] == k {
				continue // no collision !
			}
			st.Coll = st.Coll + 1
			var s int
			for s = 1; s< maxin && mm.keys[(i + s)& (maxin-1)] != k; s++  {
				// loop until search succeeds or maxin reached
			}
			// s now contains the nb of searches that was required ...
			st.Sumsearch = st.Sumsearch + s
			st.Maxsearch = max(st.Maxsearch,s)
			}
		}
		return st
	}